#!/bin/sh

CHAIN_DIR="/root/contract"
CHAIN_BIN=$CHAIN_DIR"/build"
LOG_PATH="/var/log/contract"

start_back() {
	nohup $CHAIN_BIN/"contractd" start --log_level warn --home n1 2>&1 > $LOG_PATH"/n1.log" &
	nohup $CHAIN_BIN/"contractd" http 8000 --chain-id contract --from user0 --home n1 2>&1 > $LOG_PATH"/http.log" &
	return 0 
}

stop_back() {
	kill -9 `pgrep -f "contractd"`
	return 0
}

status() {
	ps -f -C nginx -C contractd
	return 0
}

restart() {
	stop_back
	sleep 1
	start_back
}


case "$1" in
	start)
	case "$2" in
	  back)
		start_back
		RETVAL=$?
		;;
	  *)
		start_back
		RETVAL=$?
		;;
	esac
	;;
	stop)
	case "$2" in
	  back)
		stop_back
		RETVAL=$?
		;;
	  *)
		stop_back
		RETVAL=$?
		;;
	esac 
	;;
	restart)
	restart
	RETVAL=$?
	;;
	status)
	status
	RETVAL=$?
	;;
	*)
	echo $"Usage: my_chain {start|stop|restart} {back|all} | status"
	RETVAL=2
	;;
esac

exit $RETVAL
